# Generated by Django 3.0.3 on 2020-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='first_images/default.png', null=True, upload_to='first_images/')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
