# Generated by Django 3.0.3 on 2020-06-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recAndgiv_images', '0004_auto_20200603_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='image_system',
            field=models.ImageField(blank=True, null=True, upload_to='recAndgiv_images/first_images'),
        ),
    ]
