# Generated by Django 3.0.3 on 2020-06-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recAndgiv_images', '0005_auto_20200603_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='image_system',
            field=models.ImageField(null=True, upload_to='recAndgiv_images/first_images'),
        ),
    ]
